### ISSUE TITLE
Blank site on iOS 12

### ISSUE THREAD

**Issue by Em-AK** [solidjs/solid-site#206] opened 2021-12-13 14:15 UTC
Loading the site on my iphone 5s, iOS 12.5.5 results in a blank page with Safari, Opera 3.2.6 (latest), Brave [1.24](https://github.com/brave/brave-ios/releases/tag/v1.24).

Is it solidjs itself that is not compatible with my hardware or just this website?
I would be happy to learn more about what exaclty it is not supported.

**Comment by aquaductape** [comment] 2021-12-16 01:04
solidjs should support iOS 12 since it supports object proxies and I remember early 1.0 version working, since I have device that runs iOS 12. The recent version of solidjs breaks on iOS 12.

It's due to a syntax error
```
SyntaxError: Unexpected token '.'
```

**Comment by davedbase** [comment] 2021-12-16 18:12
@aquaductape I'll try running this in simulator with logging. I'm thinking this is not a SolidJS core issue but could simply be a solid-site specific bug on those devices.

@Em-AK I checked in with core and there's nothing known that would prohibit Solid use on those devices. We're investigating though in case it is an issue we could potentially have a patch in the next 1.3 release.

**Comment by amoutonbrady** [comment] 2021-12-17 08:48
Hey, for the record, I ran a [browserstack](https://www.browserstack.com/) iPhone on iOs 12 with Safari and could reproduce the bug. The "good" part is that, in that service we have access to the dev console. The "bad" part is that the error is cryptic and we have no source maps.

Here's the screenshots :

![image](https://user-images.githubusercontent.com/17355226/146515877-58f87aee-4455-462c-9ea6-23c5fc7ff58a.png)

```
SyntaxError: Unexpected token '.'
    promiseRejectionJob @ (program): 1
```

I couldn't find anything with a quick Google search but I think this is most likely related to the Solid website and not the core.
If I was to guess, I'd say this might be due to our target build in the vite config being `esnext`: https://github.com/solidjs/solid-site/blob/master/vite.config.ts#L69

**Closed** 2022-02-12 20:54 UTC
