### ISSUE TITLE
Introduction/Signals tutorial does not work in Firefox

### ISSUE THREAD

**Issue by lectrician1** [solidjs/solid-site#451] opened 2023-03-28 12:49 UTC
https://www.solidjs.com/tutorial/introduction_signals?solved does not show changes to the count in the Result window in Firefox 113.0a1, however, it works in Chrome, and in Firefox when it is pasted to the Playground.

**Comment by modderme123** [comment] 2023-09-15 18:42
This sounds like a phantom timing issue that no longer seems to be a problem, closing because I can't seem to reproduce this

**Closed by modderme123** 2023-09-15 18:42 UTC
